[2024-11-03T00:00:08.218+0000] {processor.py:186} INFO - Started process (PID=817) to work on /opt/airflow/dags/stock_data_pipeline.py
[2024-11-03T00:00:08.219+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_data_pipeline.py for tasks to queue
[2024-11-03T00:00:08.221+0000] {logging_mixin.py:190} INFO - [2024-11-03T00:00:08.221+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/stock_data_pipeline.py
[2024-11-03T00:00:08.233+0000] {logging_mixin.py:190} INFO - [2024-11-03T00:00:08.230+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/stock_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_data_pipeline.py", line 4, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2024-11-03T00:00:08.235+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_data_pipeline.py
[2024-11-03T00:00:08.250+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_data_pipeline.py took 0.037 seconds
[2024-11-03T00:00:38.907+0000] {processor.py:186} INFO - Started process (PID=880) to work on /opt/airflow/dags/stock_data_pipeline.py
[2024-11-03T00:00:38.908+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_data_pipeline.py for tasks to queue
[2024-11-03T00:00:38.910+0000] {logging_mixin.py:190} INFO - [2024-11-03T00:00:38.909+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/stock_data_pipeline.py
[2024-11-03T00:00:38.921+0000] {logging_mixin.py:190} INFO - [2024-11-03T00:00:38.919+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/stock_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_data_pipeline.py", line 4, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2024-11-03T00:00:38.922+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_data_pipeline.py
[2024-11-03T00:00:38.937+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_data_pipeline.py took 0.035 seconds
[2024-11-03T00:01:09.925+0000] {processor.py:186} INFO - Started process (PID=943) to work on /opt/airflow/dags/stock_data_pipeline.py
[2024-11-03T00:01:09.926+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_data_pipeline.py for tasks to queue
[2024-11-03T00:01:09.928+0000] {logging_mixin.py:190} INFO - [2024-11-03T00:01:09.928+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/stock_data_pipeline.py
[2024-11-03T00:01:09.940+0000] {logging_mixin.py:190} INFO - [2024-11-03T00:01:09.937+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/stock_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_data_pipeline.py", line 4, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2024-11-03T00:01:09.941+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_data_pipeline.py
[2024-11-03T00:01:09.956+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_data_pipeline.py took 0.035 seconds
[2024-11-03T00:01:40.312+0000] {processor.py:186} INFO - Started process (PID=1006) to work on /opt/airflow/dags/stock_data_pipeline.py
[2024-11-03T00:01:40.313+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_data_pipeline.py for tasks to queue
[2024-11-03T00:01:40.316+0000] {logging_mixin.py:190} INFO - [2024-11-03T00:01:40.315+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/stock_data_pipeline.py
[2024-11-03T00:47:58.818+0000] {processor.py:186} INFO - Started process (PID=59) to work on /opt/airflow/dags/stock_data_pipeline.py
[2024-11-03T00:47:58.820+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_data_pipeline.py for tasks to queue
[2024-11-03T00:47:58.822+0000] {logging_mixin.py:190} INFO - [2024-11-03T00:47:58.822+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/stock_data_pipeline.py
[2024-11-03T00:47:58.843+0000] {logging_mixin.py:190} INFO - [2024-11-03T00:47:58.839+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/stock_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_data_pipeline.py", line 4, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2024-11-03T00:47:58.844+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_data_pipeline.py
[2024-11-03T00:47:58.883+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_data_pipeline.py took 0.070 seconds
[2024-11-03T00:48:29.063+0000] {processor.py:186} INFO - Started process (PID=122) to work on /opt/airflow/dags/stock_data_pipeline.py
[2024-11-03T00:48:29.064+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_data_pipeline.py for tasks to queue
[2024-11-03T00:48:29.065+0000] {logging_mixin.py:190} INFO - [2024-11-03T00:48:29.065+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/stock_data_pipeline.py
[2024-11-03T00:48:29.077+0000] {logging_mixin.py:190} INFO - [2024-11-03T00:48:29.075+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/stock_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_data_pipeline.py", line 4, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2024-11-03T00:48:29.078+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_data_pipeline.py
[2024-11-03T00:48:29.094+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_data_pipeline.py took 0.035 seconds
[2024-11-03T00:48:59.272+0000] {processor.py:186} INFO - Started process (PID=185) to work on /opt/airflow/dags/stock_data_pipeline.py
[2024-11-03T00:48:59.272+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_data_pipeline.py for tasks to queue
[2024-11-03T00:48:59.274+0000] {logging_mixin.py:190} INFO - [2024-11-03T00:48:59.274+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/stock_data_pipeline.py
[2024-11-03T00:48:59.286+0000] {logging_mixin.py:190} INFO - [2024-11-03T00:48:59.283+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/stock_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_data_pipeline.py", line 4, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2024-11-03T00:48:59.287+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_data_pipeline.py
[2024-11-03T00:48:59.303+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_data_pipeline.py took 0.035 seconds
[2024-11-03T00:49:29.651+0000] {processor.py:186} INFO - Started process (PID=248) to work on /opt/airflow/dags/stock_data_pipeline.py
[2024-11-03T00:49:29.652+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_data_pipeline.py for tasks to queue
[2024-11-03T00:49:29.654+0000] {logging_mixin.py:190} INFO - [2024-11-03T00:49:29.653+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/stock_data_pipeline.py
[2024-11-03T00:49:29.667+0000] {logging_mixin.py:190} INFO - [2024-11-03T00:49:29.664+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/stock_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_data_pipeline.py", line 4, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2024-11-03T00:49:29.668+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_data_pipeline.py
[2024-11-03T00:49:29.684+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_data_pipeline.py took 0.037 seconds
[2024-11-03T00:50:00.054+0000] {processor.py:186} INFO - Started process (PID=311) to work on /opt/airflow/dags/stock_data_pipeline.py
[2024-11-03T00:50:00.054+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_data_pipeline.py for tasks to queue
[2024-11-03T00:50:00.057+0000] {logging_mixin.py:190} INFO - [2024-11-03T00:50:00.056+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/stock_data_pipeline.py
[2024-11-03T00:50:00.070+0000] {logging_mixin.py:190} INFO - [2024-11-03T00:50:00.067+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/stock_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_data_pipeline.py", line 4, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2024-11-03T00:50:00.071+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_data_pipeline.py
[2024-11-03T00:50:00.087+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_data_pipeline.py took 0.039 seconds
[2024-11-03T00:50:30.628+0000] {processor.py:186} INFO - Started process (PID=374) to work on /opt/airflow/dags/stock_data_pipeline.py
[2024-11-03T00:50:30.629+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_data_pipeline.py for tasks to queue
[2024-11-03T00:50:30.631+0000] {logging_mixin.py:190} INFO - [2024-11-03T00:50:30.631+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/stock_data_pipeline.py
[2024-11-03T00:50:30.643+0000] {logging_mixin.py:190} INFO - [2024-11-03T00:50:30.640+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/stock_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_data_pipeline.py", line 4, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2024-11-03T00:50:30.644+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_data_pipeline.py
[2024-11-03T00:50:30.659+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_data_pipeline.py took 0.035 seconds
[2024-11-03T00:51:01.153+0000] {processor.py:186} INFO - Started process (PID=437) to work on /opt/airflow/dags/stock_data_pipeline.py
[2024-11-03T00:51:01.154+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_data_pipeline.py for tasks to queue
[2024-11-03T00:51:01.156+0000] {logging_mixin.py:190} INFO - [2024-11-03T00:51:01.155+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/stock_data_pipeline.py
[2024-11-03T00:51:01.168+0000] {logging_mixin.py:190} INFO - [2024-11-03T00:51:01.165+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/stock_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_data_pipeline.py", line 4, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2024-11-03T00:51:01.169+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_data_pipeline.py
[2024-11-03T00:51:01.184+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_data_pipeline.py took 0.035 seconds
[2024-11-03T00:51:31.549+0000] {processor.py:186} INFO - Started process (PID=500) to work on /opt/airflow/dags/stock_data_pipeline.py
[2024-11-03T00:51:31.549+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_data_pipeline.py for tasks to queue
[2024-11-03T00:51:31.551+0000] {logging_mixin.py:190} INFO - [2024-11-03T00:51:31.551+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/stock_data_pipeline.py
[2024-11-03T00:51:31.564+0000] {logging_mixin.py:190} INFO - [2024-11-03T00:51:31.561+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/stock_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_data_pipeline.py", line 4, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2024-11-03T00:51:31.565+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_data_pipeline.py
[2024-11-03T00:51:31.581+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_data_pipeline.py took 0.036 seconds
[2024-11-03T00:52:02.042+0000] {processor.py:186} INFO - Started process (PID=563) to work on /opt/airflow/dags/stock_data_pipeline.py
[2024-11-03T00:52:02.042+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_data_pipeline.py for tasks to queue
[2024-11-03T00:52:02.044+0000] {logging_mixin.py:190} INFO - [2024-11-03T00:52:02.044+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/stock_data_pipeline.py
[2024-11-03T00:52:02.056+0000] {logging_mixin.py:190} INFO - [2024-11-03T00:52:02.053+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/stock_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_data_pipeline.py", line 4, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2024-11-03T00:52:02.057+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_data_pipeline.py
[2024-11-03T00:52:02.073+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_data_pipeline.py took 0.035 seconds
[2024-11-03T00:52:32.383+0000] {processor.py:186} INFO - Started process (PID=626) to work on /opt/airflow/dags/stock_data_pipeline.py
[2024-11-03T00:52:32.383+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_data_pipeline.py for tasks to queue
[2024-11-03T00:52:32.385+0000] {logging_mixin.py:190} INFO - [2024-11-03T00:52:32.385+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/stock_data_pipeline.py
[2024-11-03T00:52:32.398+0000] {logging_mixin.py:190} INFO - [2024-11-03T00:52:32.395+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/stock_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_data_pipeline.py", line 4, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2024-11-03T00:52:32.399+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_data_pipeline.py
[2024-11-03T00:52:32.415+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_data_pipeline.py took 0.037 seconds
[2024-11-03T00:53:02.785+0000] {processor.py:186} INFO - Started process (PID=695) to work on /opt/airflow/dags/stock_data_pipeline.py
[2024-11-03T00:53:02.786+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_data_pipeline.py for tasks to queue
[2024-11-03T00:53:02.789+0000] {logging_mixin.py:190} INFO - [2024-11-03T00:53:02.788+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/stock_data_pipeline.py
[2024-11-03T00:53:02.802+0000] {logging_mixin.py:190} INFO - [2024-11-03T00:53:02.799+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/stock_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_data_pipeline.py", line 4, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2024-11-03T00:53:02.803+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_data_pipeline.py
[2024-11-03T00:53:02.819+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_data_pipeline.py took 0.039 seconds
[2024-11-03T00:53:32.971+0000] {processor.py:186} INFO - Started process (PID=758) to work on /opt/airflow/dags/stock_data_pipeline.py
[2024-11-03T00:53:32.972+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_data_pipeline.py for tasks to queue
[2024-11-03T00:53:32.974+0000] {logging_mixin.py:190} INFO - [2024-11-03T00:53:32.974+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/stock_data_pipeline.py
[2024-11-03T00:53:32.987+0000] {logging_mixin.py:190} INFO - [2024-11-03T00:53:32.984+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/stock_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_data_pipeline.py", line 4, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2024-11-03T00:53:32.988+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_data_pipeline.py
[2024-11-03T00:53:33.005+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_data_pipeline.py took 0.039 seconds
[2024-11-03T00:54:03.451+0000] {processor.py:186} INFO - Started process (PID=821) to work on /opt/airflow/dags/stock_data_pipeline.py
[2024-11-03T00:54:03.452+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_data_pipeline.py for tasks to queue
[2024-11-03T00:54:03.454+0000] {logging_mixin.py:190} INFO - [2024-11-03T00:54:03.454+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/stock_data_pipeline.py
[2024-11-03T00:54:03.471+0000] {logging_mixin.py:190} INFO - [2024-11-03T00:54:03.467+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/stock_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_data_pipeline.py", line 4, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2024-11-03T00:54:03.472+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_data_pipeline.py
[2024-11-03T00:54:03.493+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_data_pipeline.py took 0.050 seconds
[2024-11-03T00:54:33.606+0000] {processor.py:186} INFO - Started process (PID=884) to work on /opt/airflow/dags/stock_data_pipeline.py
[2024-11-03T00:54:33.607+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_data_pipeline.py for tasks to queue
[2024-11-03T00:54:33.609+0000] {logging_mixin.py:190} INFO - [2024-11-03T00:54:33.609+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/stock_data_pipeline.py
[2024-11-03T00:54:33.623+0000] {logging_mixin.py:190} INFO - [2024-11-03T00:54:33.619+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/stock_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_data_pipeline.py", line 4, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2024-11-03T00:54:33.624+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_data_pipeline.py
[2024-11-03T00:54:33.643+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_data_pipeline.py took 0.041 seconds
[2024-11-03T00:55:04.051+0000] {processor.py:186} INFO - Started process (PID=947) to work on /opt/airflow/dags/stock_data_pipeline.py
[2024-11-03T00:55:04.052+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_data_pipeline.py for tasks to queue
[2024-11-03T00:55:04.053+0000] {logging_mixin.py:190} INFO - [2024-11-03T00:55:04.053+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/stock_data_pipeline.py
[2024-11-03T00:55:04.066+0000] {logging_mixin.py:190} INFO - [2024-11-03T00:55:04.063+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/stock_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_data_pipeline.py", line 4, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2024-11-03T00:55:04.068+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_data_pipeline.py
[2024-11-03T00:55:04.085+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_data_pipeline.py took 0.039 seconds
[2024-11-03T00:55:34.385+0000] {processor.py:186} INFO - Started process (PID=1010) to work on /opt/airflow/dags/stock_data_pipeline.py
[2024-11-03T00:55:34.386+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_data_pipeline.py for tasks to queue
[2024-11-03T00:55:34.388+0000] {logging_mixin.py:190} INFO - [2024-11-03T00:55:34.387+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/stock_data_pipeline.py
[2024-11-03T00:55:34.400+0000] {logging_mixin.py:190} INFO - [2024-11-03T00:55:34.397+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/stock_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_data_pipeline.py", line 4, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2024-11-03T00:55:34.401+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_data_pipeline.py
[2024-11-03T00:55:34.417+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_data_pipeline.py took 0.036 seconds
[2024-11-03T00:56:05.035+0000] {processor.py:186} INFO - Started process (PID=1073) to work on /opt/airflow/dags/stock_data_pipeline.py
[2024-11-03T00:56:05.036+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_data_pipeline.py for tasks to queue
[2024-11-03T00:56:05.038+0000] {logging_mixin.py:190} INFO - [2024-11-03T00:56:05.038+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/stock_data_pipeline.py
[2024-11-03T00:56:05.051+0000] {logging_mixin.py:190} INFO - [2024-11-03T00:56:05.048+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/stock_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_data_pipeline.py", line 4, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2024-11-03T00:56:05.052+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_data_pipeline.py
[2024-11-03T00:56:05.068+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_data_pipeline.py took 0.037 seconds
[2024-11-03T00:56:35.480+0000] {processor.py:186} INFO - Started process (PID=1136) to work on /opt/airflow/dags/stock_data_pipeline.py
[2024-11-03T00:56:35.480+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_data_pipeline.py for tasks to queue
[2024-11-03T00:56:35.483+0000] {logging_mixin.py:190} INFO - [2024-11-03T00:56:35.482+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/stock_data_pipeline.py
[2024-11-03T00:56:35.495+0000] {logging_mixin.py:190} INFO - [2024-11-03T00:56:35.492+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/stock_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_data_pipeline.py", line 4, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2024-11-03T00:56:35.496+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_data_pipeline.py
[2024-11-03T00:56:35.511+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_data_pipeline.py took 0.036 seconds
[2024-11-03T00:57:05.669+0000] {processor.py:186} INFO - Started process (PID=1199) to work on /opt/airflow/dags/stock_data_pipeline.py
[2024-11-03T00:57:05.670+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_data_pipeline.py for tasks to queue
[2024-11-03T00:57:05.672+0000] {logging_mixin.py:190} INFO - [2024-11-03T00:57:05.672+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/stock_data_pipeline.py
[2024-11-03T00:57:05.685+0000] {logging_mixin.py:190} INFO - [2024-11-03T00:57:05.682+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/stock_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_data_pipeline.py", line 4, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2024-11-03T00:57:05.686+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_data_pipeline.py
[2024-11-03T00:57:05.704+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_data_pipeline.py took 0.041 seconds
[2024-11-03T00:57:36.151+0000] {processor.py:186} INFO - Started process (PID=1262) to work on /opt/airflow/dags/stock_data_pipeline.py
[2024-11-03T00:57:36.152+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_data_pipeline.py for tasks to queue
[2024-11-03T00:57:36.154+0000] {logging_mixin.py:190} INFO - [2024-11-03T00:57:36.154+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/stock_data_pipeline.py
[2024-11-03T00:57:36.166+0000] {logging_mixin.py:190} INFO - [2024-11-03T00:57:36.163+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/stock_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_data_pipeline.py", line 4, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2024-11-03T00:57:36.167+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_data_pipeline.py
[2024-11-03T00:57:36.184+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_data_pipeline.py took 0.037 seconds
[2024-11-03T00:58:06.308+0000] {processor.py:186} INFO - Started process (PID=1325) to work on /opt/airflow/dags/stock_data_pipeline.py
[2024-11-03T00:58:06.309+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_data_pipeline.py for tasks to queue
[2024-11-03T00:58:06.311+0000] {logging_mixin.py:190} INFO - [2024-11-03T00:58:06.310+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/stock_data_pipeline.py
[2024-11-03T00:58:06.323+0000] {logging_mixin.py:190} INFO - [2024-11-03T00:58:06.320+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/stock_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_data_pipeline.py", line 4, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2024-11-03T00:58:06.324+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_data_pipeline.py
[2024-11-03T00:58:06.342+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_data_pipeline.py took 0.039 seconds
[2024-11-03T00:58:36.702+0000] {processor.py:186} INFO - Started process (PID=1388) to work on /opt/airflow/dags/stock_data_pipeline.py
[2024-11-03T00:58:36.703+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_data_pipeline.py for tasks to queue
[2024-11-03T00:58:36.705+0000] {logging_mixin.py:190} INFO - [2024-11-03T00:58:36.704+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/stock_data_pipeline.py
[2024-11-03T00:58:36.718+0000] {logging_mixin.py:190} INFO - [2024-11-03T00:58:36.715+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/stock_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_data_pipeline.py", line 4, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2024-11-03T00:58:36.719+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_data_pipeline.py
[2024-11-03T00:58:36.734+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_data_pipeline.py took 0.037 seconds
[2024-11-03T00:59:06.942+0000] {processor.py:186} INFO - Started process (PID=1451) to work on /opt/airflow/dags/stock_data_pipeline.py
[2024-11-03T00:59:06.943+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_data_pipeline.py for tasks to queue
[2024-11-03T00:59:06.944+0000] {logging_mixin.py:190} INFO - [2024-11-03T00:59:06.944+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/stock_data_pipeline.py
[2024-11-03T00:59:06.957+0000] {logging_mixin.py:190} INFO - [2024-11-03T00:59:06.954+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/stock_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_data_pipeline.py", line 4, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2024-11-03T00:59:06.957+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_data_pipeline.py
[2024-11-03T00:59:06.973+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_data_pipeline.py took 0.035 seconds
[2024-11-03T00:59:37.477+0000] {processor.py:186} INFO - Started process (PID=1514) to work on /opt/airflow/dags/stock_data_pipeline.py
[2024-11-03T00:59:37.478+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_data_pipeline.py for tasks to queue
[2024-11-03T00:59:37.480+0000] {logging_mixin.py:190} INFO - [2024-11-03T00:59:37.479+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/stock_data_pipeline.py
[2024-11-03T00:59:37.492+0000] {logging_mixin.py:190} INFO - [2024-11-03T00:59:37.489+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/stock_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_data_pipeline.py", line 4, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2024-11-03T00:59:37.493+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_data_pipeline.py
[2024-11-03T00:59:37.509+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_data_pipeline.py took 0.036 seconds
[2024-11-03T01:00:07.667+0000] {processor.py:186} INFO - Started process (PID=1577) to work on /opt/airflow/dags/stock_data_pipeline.py
[2024-11-03T01:00:07.668+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_data_pipeline.py for tasks to queue
[2024-11-03T01:00:07.670+0000] {logging_mixin.py:190} INFO - [2024-11-03T01:00:07.670+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/stock_data_pipeline.py
[2024-11-03T01:00:07.682+0000] {logging_mixin.py:190} INFO - [2024-11-03T01:00:07.679+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/stock_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_data_pipeline.py", line 4, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2024-11-03T01:00:07.683+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_data_pipeline.py
[2024-11-03T01:00:07.699+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_data_pipeline.py took 0.036 seconds
[2024-11-03T01:00:38.339+0000] {processor.py:186} INFO - Started process (PID=1640) to work on /opt/airflow/dags/stock_data_pipeline.py
[2024-11-03T01:00:38.339+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_data_pipeline.py for tasks to queue
[2024-11-03T01:00:38.341+0000] {logging_mixin.py:190} INFO - [2024-11-03T01:00:38.341+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/stock_data_pipeline.py
[2024-11-03T01:00:38.354+0000] {logging_mixin.py:190} INFO - [2024-11-03T01:00:38.351+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/stock_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_data_pipeline.py", line 4, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2024-11-03T01:00:38.355+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_data_pipeline.py
[2024-11-03T01:00:38.371+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_data_pipeline.py took 0.037 seconds
[2024-11-03T01:01:08.824+0000] {processor.py:186} INFO - Started process (PID=1703) to work on /opt/airflow/dags/stock_data_pipeline.py
[2024-11-03T01:01:08.825+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_data_pipeline.py for tasks to queue
[2024-11-03T01:01:08.827+0000] {logging_mixin.py:190} INFO - [2024-11-03T01:01:08.827+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/stock_data_pipeline.py
[2024-11-03T01:01:08.839+0000] {logging_mixin.py:190} INFO - [2024-11-03T01:01:08.836+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/stock_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_data_pipeline.py", line 4, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2024-11-03T01:01:08.840+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_data_pipeline.py
[2024-11-03T01:01:08.856+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_data_pipeline.py took 0.036 seconds
[2024-11-03T01:01:39.344+0000] {processor.py:186} INFO - Started process (PID=1766) to work on /opt/airflow/dags/stock_data_pipeline.py
[2024-11-03T01:01:39.345+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_data_pipeline.py for tasks to queue
[2024-11-03T01:01:39.346+0000] {logging_mixin.py:190} INFO - [2024-11-03T01:01:39.346+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/stock_data_pipeline.py
[2024-11-03T01:01:39.360+0000] {logging_mixin.py:190} INFO - [2024-11-03T01:01:39.357+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/stock_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_data_pipeline.py", line 4, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2024-11-03T01:01:39.361+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_data_pipeline.py
[2024-11-03T01:01:39.377+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_data_pipeline.py took 0.038 seconds
[2024-11-03T01:02:09.772+0000] {processor.py:186} INFO - Started process (PID=1829) to work on /opt/airflow/dags/stock_data_pipeline.py
[2024-11-03T01:02:09.772+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_data_pipeline.py for tasks to queue
[2024-11-03T01:02:09.774+0000] {logging_mixin.py:190} INFO - [2024-11-03T01:02:09.774+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/stock_data_pipeline.py
[2024-11-03T01:02:09.787+0000] {logging_mixin.py:190} INFO - [2024-11-03T01:02:09.784+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/stock_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_data_pipeline.py", line 4, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2024-11-03T01:02:09.788+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_data_pipeline.py
[2024-11-03T01:02:09.803+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_data_pipeline.py took 0.036 seconds
[2024-11-03T01:02:39.968+0000] {processor.py:186} INFO - Started process (PID=1892) to work on /opt/airflow/dags/stock_data_pipeline.py
[2024-11-03T01:02:39.969+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_data_pipeline.py for tasks to queue
[2024-11-03T01:02:39.971+0000] {logging_mixin.py:190} INFO - [2024-11-03T01:02:39.971+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/stock_data_pipeline.py
[2024-11-03T01:02:39.985+0000] {logging_mixin.py:190} INFO - [2024-11-03T01:02:39.982+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/stock_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_data_pipeline.py", line 4, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2024-11-03T01:02:39.986+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_data_pipeline.py
[2024-11-03T01:02:40.001+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_data_pipeline.py took 0.037 seconds
[2024-11-03T01:03:10.367+0000] {processor.py:186} INFO - Started process (PID=1955) to work on /opt/airflow/dags/stock_data_pipeline.py
[2024-11-03T01:03:10.367+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_data_pipeline.py for tasks to queue
[2024-11-03T01:03:10.369+0000] {logging_mixin.py:190} INFO - [2024-11-03T01:03:10.369+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/stock_data_pipeline.py
[2024-11-03T01:03:10.383+0000] {logging_mixin.py:190} INFO - [2024-11-03T01:03:10.379+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/stock_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_data_pipeline.py", line 4, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2024-11-03T01:03:10.384+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_data_pipeline.py
[2024-11-03T01:03:10.401+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_data_pipeline.py took 0.039 seconds
[2024-11-03T01:03:40.948+0000] {processor.py:186} INFO - Started process (PID=2018) to work on /opt/airflow/dags/stock_data_pipeline.py
[2024-11-03T01:03:40.949+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_data_pipeline.py for tasks to queue
[2024-11-03T01:03:40.951+0000] {logging_mixin.py:190} INFO - [2024-11-03T01:03:40.950+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/stock_data_pipeline.py
[2024-11-03T01:03:40.963+0000] {logging_mixin.py:190} INFO - [2024-11-03T01:03:40.960+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/stock_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_data_pipeline.py", line 4, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2024-11-03T01:03:40.964+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_data_pipeline.py
[2024-11-03T01:03:40.980+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_data_pipeline.py took 0.036 seconds
[2024-11-03T01:04:11.904+0000] {processor.py:186} INFO - Started process (PID=2081) to work on /opt/airflow/dags/stock_data_pipeline.py
[2024-11-03T01:04:11.904+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_data_pipeline.py for tasks to queue
[2024-11-03T01:04:11.906+0000] {logging_mixin.py:190} INFO - [2024-11-03T01:04:11.906+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/stock_data_pipeline.py
[2024-11-03T01:04:11.919+0000] {logging_mixin.py:190} INFO - [2024-11-03T01:04:11.916+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/stock_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_data_pipeline.py", line 4, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2024-11-03T01:04:11.920+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_data_pipeline.py
[2024-11-03T01:04:11.937+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_data_pipeline.py took 0.038 seconds
[2024-11-03T01:04:42.624+0000] {processor.py:186} INFO - Started process (PID=2144) to work on /opt/airflow/dags/stock_data_pipeline.py
[2024-11-03T01:04:42.625+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_data_pipeline.py for tasks to queue
[2024-11-03T01:04:42.627+0000] {logging_mixin.py:190} INFO - [2024-11-03T01:04:42.626+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/stock_data_pipeline.py
[2024-11-03T01:04:42.639+0000] {logging_mixin.py:190} INFO - [2024-11-03T01:04:42.636+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/stock_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_data_pipeline.py", line 4, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2024-11-03T01:04:42.641+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_data_pipeline.py
[2024-11-03T01:04:42.658+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_data_pipeline.py took 0.038 seconds
[2024-11-03T01:05:13.123+0000] {processor.py:186} INFO - Started process (PID=2207) to work on /opt/airflow/dags/stock_data_pipeline.py
[2024-11-03T01:05:13.124+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_data_pipeline.py for tasks to queue
[2024-11-03T01:05:13.126+0000] {logging_mixin.py:190} INFO - [2024-11-03T01:05:13.126+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/stock_data_pipeline.py
[2024-11-03T01:05:13.138+0000] {logging_mixin.py:190} INFO - [2024-11-03T01:05:13.135+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/stock_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_data_pipeline.py", line 4, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2024-11-03T01:05:13.139+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_data_pipeline.py
[2024-11-03T01:05:13.154+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_data_pipeline.py took 0.035 seconds
[2024-11-03T01:05:43.748+0000] {processor.py:186} INFO - Started process (PID=2270) to work on /opt/airflow/dags/stock_data_pipeline.py
[2024-11-03T01:05:43.749+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_data_pipeline.py for tasks to queue
[2024-11-03T01:05:43.751+0000] {logging_mixin.py:190} INFO - [2024-11-03T01:05:43.751+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/stock_data_pipeline.py
[2024-11-03T01:05:43.764+0000] {logging_mixin.py:190} INFO - [2024-11-03T01:05:43.761+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/stock_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_data_pipeline.py", line 4, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2024-11-03T01:05:43.765+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_data_pipeline.py
[2024-11-03T01:05:43.780+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_data_pipeline.py took 0.036 seconds
[2024-11-03T01:06:14.197+0000] {processor.py:186} INFO - Started process (PID=2333) to work on /opt/airflow/dags/stock_data_pipeline.py
[2024-11-03T01:06:14.197+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_data_pipeline.py for tasks to queue
[2024-11-03T01:06:14.199+0000] {logging_mixin.py:190} INFO - [2024-11-03T01:06:14.199+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/stock_data_pipeline.py
[2024-11-03T01:06:14.213+0000] {logging_mixin.py:190} INFO - [2024-11-03T01:06:14.210+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/stock_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_data_pipeline.py", line 4, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2024-11-03T01:06:14.214+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_data_pipeline.py
[2024-11-03T01:06:14.230+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_data_pipeline.py took 0.038 seconds
