[2024-11-02T20:45:52.482+0000] {processor.py:186} INFO - Started process (PID=2540) to work on /opt/airflow/dags/stock_data_pipeline.py
[2024-11-02T20:45:52.483+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_data_pipeline.py for tasks to queue
[2024-11-02T20:45:52.484+0000] {logging_mixin.py:190} INFO - [2024-11-02T20:45:52.484+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/stock_data_pipeline.py
[2024-11-02T20:45:52.504+0000] {logging_mixin.py:190} INFO - [2024-11-02T20:45:52.501+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/stock_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_data_pipeline.py", line 4, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2024-11-02T20:45:52.505+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_data_pipeline.py
[2024-11-02T20:45:52.522+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_data_pipeline.py took 0.045 seconds
[2024-11-02T20:46:23.271+0000] {processor.py:186} INFO - Started process (PID=2603) to work on /opt/airflow/dags/stock_data_pipeline.py
[2024-11-02T20:46:23.272+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_data_pipeline.py for tasks to queue
[2024-11-02T20:46:23.274+0000] {logging_mixin.py:190} INFO - [2024-11-02T20:46:23.274+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/stock_data_pipeline.py
[2024-11-02T20:46:23.287+0000] {logging_mixin.py:190} INFO - [2024-11-02T20:46:23.284+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/stock_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_data_pipeline.py", line 4, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2024-11-02T20:46:23.288+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_data_pipeline.py
[2024-11-02T20:46:23.303+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_data_pipeline.py took 0.036 seconds
[2024-11-02T20:46:53.909+0000] {processor.py:186} INFO - Started process (PID=2666) to work on /opt/airflow/dags/stock_data_pipeline.py
[2024-11-02T20:46:53.909+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_data_pipeline.py for tasks to queue
[2024-11-02T20:46:53.911+0000] {logging_mixin.py:190} INFO - [2024-11-02T20:46:53.911+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/stock_data_pipeline.py
[2024-11-02T20:46:53.924+0000] {logging_mixin.py:190} INFO - [2024-11-02T20:46:53.922+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/stock_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_data_pipeline.py", line 4, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2024-11-02T20:46:53.925+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_data_pipeline.py
[2024-11-02T20:46:53.940+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_data_pipeline.py took 0.036 seconds
[2024-11-02T20:47:24.688+0000] {processor.py:186} INFO - Started process (PID=2729) to work on /opt/airflow/dags/stock_data_pipeline.py
[2024-11-02T20:47:24.689+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_data_pipeline.py for tasks to queue
[2024-11-02T20:47:24.690+0000] {logging_mixin.py:190} INFO - [2024-11-02T20:47:24.690+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/stock_data_pipeline.py
[2024-11-02T20:47:24.703+0000] {logging_mixin.py:190} INFO - [2024-11-02T20:47:24.700+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/stock_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_data_pipeline.py", line 4, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2024-11-02T20:47:24.704+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_data_pipeline.py
[2024-11-02T20:47:24.720+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_data_pipeline.py took 0.036 seconds
[2024-11-02T20:47:55.414+0000] {processor.py:186} INFO - Started process (PID=2792) to work on /opt/airflow/dags/stock_data_pipeline.py
[2024-11-02T20:47:55.415+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_data_pipeline.py for tasks to queue
[2024-11-02T20:47:55.416+0000] {logging_mixin.py:190} INFO - [2024-11-02T20:47:55.416+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/stock_data_pipeline.py
[2024-11-02T20:47:55.429+0000] {logging_mixin.py:190} INFO - [2024-11-02T20:47:55.426+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/stock_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_data_pipeline.py", line 4, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2024-11-02T20:47:55.430+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_data_pipeline.py
[2024-11-02T20:47:55.445+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_data_pipeline.py took 0.036 seconds
[2024-11-02T20:48:26.165+0000] {processor.py:186} INFO - Started process (PID=2855) to work on /opt/airflow/dags/stock_data_pipeline.py
[2024-11-02T20:48:26.166+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_data_pipeline.py for tasks to queue
[2024-11-02T20:48:26.168+0000] {logging_mixin.py:190} INFO - [2024-11-02T20:48:26.167+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/stock_data_pipeline.py
[2024-11-02T20:48:26.180+0000] {logging_mixin.py:190} INFO - [2024-11-02T20:48:26.178+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/stock_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_data_pipeline.py", line 4, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2024-11-02T20:48:26.181+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_data_pipeline.py
[2024-11-02T20:48:26.197+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_data_pipeline.py took 0.037 seconds
[2024-11-02T20:48:56.803+0000] {processor.py:186} INFO - Started process (PID=2924) to work on /opt/airflow/dags/stock_data_pipeline.py
[2024-11-02T20:48:56.804+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_data_pipeline.py for tasks to queue
[2024-11-02T20:48:56.806+0000] {logging_mixin.py:190} INFO - [2024-11-02T20:48:56.806+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/stock_data_pipeline.py
[2024-11-02T20:48:56.819+0000] {logging_mixin.py:190} INFO - [2024-11-02T20:48:56.817+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/stock_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_data_pipeline.py", line 4, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2024-11-02T20:48:56.820+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_data_pipeline.py
[2024-11-02T20:48:56.835+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_data_pipeline.py took 0.036 seconds
[2024-11-02T20:49:27.486+0000] {processor.py:186} INFO - Started process (PID=2987) to work on /opt/airflow/dags/stock_data_pipeline.py
[2024-11-02T20:49:27.487+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_data_pipeline.py for tasks to queue
[2024-11-02T20:49:27.488+0000] {logging_mixin.py:190} INFO - [2024-11-02T20:49:27.488+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/stock_data_pipeline.py
[2024-11-02T20:49:27.501+0000] {logging_mixin.py:190} INFO - [2024-11-02T20:49:27.499+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/stock_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_data_pipeline.py", line 4, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2024-11-02T20:49:27.502+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_data_pipeline.py
[2024-11-02T20:49:27.518+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_data_pipeline.py took 0.036 seconds
[2024-11-02T20:49:58.420+0000] {processor.py:186} INFO - Started process (PID=3050) to work on /opt/airflow/dags/stock_data_pipeline.py
[2024-11-02T20:49:58.421+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_data_pipeline.py for tasks to queue
[2024-11-02T20:49:58.423+0000] {logging_mixin.py:190} INFO - [2024-11-02T20:49:58.422+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/stock_data_pipeline.py
[2024-11-02T20:49:58.436+0000] {logging_mixin.py:190} INFO - [2024-11-02T20:49:58.433+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/stock_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_data_pipeline.py", line 4, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2024-11-02T20:49:58.437+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_data_pipeline.py
[2024-11-02T20:49:58.453+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_data_pipeline.py took 0.037 seconds
[2024-11-02T20:50:28.556+0000] {processor.py:186} INFO - Started process (PID=3113) to work on /opt/airflow/dags/stock_data_pipeline.py
[2024-11-02T20:50:28.557+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_data_pipeline.py for tasks to queue
[2024-11-02T20:50:28.559+0000] {logging_mixin.py:190} INFO - [2024-11-02T20:50:28.558+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/stock_data_pipeline.py
[2024-11-02T20:50:28.572+0000] {logging_mixin.py:190} INFO - [2024-11-02T20:50:28.569+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/stock_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_data_pipeline.py", line 4, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2024-11-02T20:50:28.573+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_data_pipeline.py
[2024-11-02T20:50:28.589+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_data_pipeline.py took 0.037 seconds
[2024-11-02T20:50:58.650+0000] {processor.py:186} INFO - Started process (PID=3176) to work on /opt/airflow/dags/stock_data_pipeline.py
[2024-11-02T20:50:58.651+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_data_pipeline.py for tasks to queue
[2024-11-02T20:50:58.653+0000] {logging_mixin.py:190} INFO - [2024-11-02T20:50:58.652+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/stock_data_pipeline.py
[2024-11-02T20:50:58.665+0000] {logging_mixin.py:190} INFO - [2024-11-02T20:50:58.663+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/stock_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_data_pipeline.py", line 4, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2024-11-02T20:50:58.666+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_data_pipeline.py
[2024-11-02T20:50:58.681+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_data_pipeline.py took 0.037 seconds
[2024-11-02T20:51:29.315+0000] {processor.py:186} INFO - Started process (PID=3239) to work on /opt/airflow/dags/stock_data_pipeline.py
[2024-11-02T20:51:29.316+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_data_pipeline.py for tasks to queue
[2024-11-02T20:51:29.318+0000] {logging_mixin.py:190} INFO - [2024-11-02T20:51:29.317+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/stock_data_pipeline.py
[2024-11-02T20:51:29.331+0000] {logging_mixin.py:190} INFO - [2024-11-02T20:51:29.328+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/stock_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_data_pipeline.py", line 4, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2024-11-02T20:51:29.332+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_data_pipeline.py
[2024-11-02T20:51:29.347+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_data_pipeline.py took 0.037 seconds
[2024-11-02T20:51:59.673+0000] {processor.py:186} INFO - Started process (PID=3302) to work on /opt/airflow/dags/stock_data_pipeline.py
[2024-11-02T20:51:59.674+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_data_pipeline.py for tasks to queue
[2024-11-02T20:51:59.676+0000] {logging_mixin.py:190} INFO - [2024-11-02T20:51:59.676+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/stock_data_pipeline.py
[2024-11-02T20:51:59.696+0000] {logging_mixin.py:190} INFO - [2024-11-02T20:51:59.693+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/stock_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_data_pipeline.py", line 4, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2024-11-02T20:51:59.697+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_data_pipeline.py
[2024-11-02T20:51:59.720+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_data_pipeline.py took 0.051 seconds
[2024-11-02T20:52:30.410+0000] {processor.py:186} INFO - Started process (PID=3365) to work on /opt/airflow/dags/stock_data_pipeline.py
[2024-11-02T20:52:30.411+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_data_pipeline.py for tasks to queue
[2024-11-02T20:52:30.413+0000] {logging_mixin.py:190} INFO - [2024-11-02T20:52:30.412+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/stock_data_pipeline.py
[2024-11-02T20:52:30.426+0000] {logging_mixin.py:190} INFO - [2024-11-02T20:52:30.423+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/stock_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_data_pipeline.py", line 4, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2024-11-02T20:52:30.427+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_data_pipeline.py
[2024-11-02T20:52:30.443+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_data_pipeline.py took 0.038 seconds
[2024-11-02T20:53:00.785+0000] {processor.py:186} INFO - Started process (PID=3428) to work on /opt/airflow/dags/stock_data_pipeline.py
[2024-11-02T20:53:00.786+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_data_pipeline.py for tasks to queue
[2024-11-02T20:53:00.789+0000] {logging_mixin.py:190} INFO - [2024-11-02T20:53:00.789+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/stock_data_pipeline.py
[2024-11-02T20:53:00.803+0000] {logging_mixin.py:190} INFO - [2024-11-02T20:53:00.800+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/stock_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_data_pipeline.py", line 4, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2024-11-02T20:53:00.804+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_data_pipeline.py
[2024-11-02T20:53:00.820+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_data_pipeline.py took 0.041 seconds
[2024-11-02T20:53:30.987+0000] {processor.py:186} INFO - Started process (PID=3491) to work on /opt/airflow/dags/stock_data_pipeline.py
[2024-11-02T20:53:30.988+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_data_pipeline.py for tasks to queue
[2024-11-02T20:53:30.990+0000] {logging_mixin.py:190} INFO - [2024-11-02T20:53:30.989+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/stock_data_pipeline.py
[2024-11-02T20:53:31.003+0000] {logging_mixin.py:190} INFO - [2024-11-02T20:53:31.000+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/stock_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_data_pipeline.py", line 4, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2024-11-02T20:53:31.004+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_data_pipeline.py
[2024-11-02T20:53:31.019+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_data_pipeline.py took 0.037 seconds
[2024-11-02T20:54:01.304+0000] {processor.py:186} INFO - Started process (PID=3554) to work on /opt/airflow/dags/stock_data_pipeline.py
[2024-11-02T20:54:01.305+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_data_pipeline.py for tasks to queue
[2024-11-02T20:54:01.307+0000] {logging_mixin.py:190} INFO - [2024-11-02T20:54:01.307+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/stock_data_pipeline.py
[2024-11-02T20:54:01.321+0000] {logging_mixin.py:190} INFO - [2024-11-02T20:54:01.318+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/stock_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_data_pipeline.py", line 4, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2024-11-02T20:54:01.322+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_data_pipeline.py
[2024-11-02T20:54:01.338+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_data_pipeline.py took 0.038 seconds
[2024-11-02T20:54:31.682+0000] {processor.py:186} INFO - Started process (PID=3617) to work on /opt/airflow/dags/stock_data_pipeline.py
[2024-11-02T20:54:31.683+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_data_pipeline.py for tasks to queue
[2024-11-02T20:54:31.685+0000] {logging_mixin.py:190} INFO - [2024-11-02T20:54:31.685+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/stock_data_pipeline.py
[2024-11-02T20:54:31.698+0000] {logging_mixin.py:190} INFO - [2024-11-02T20:54:31.696+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/stock_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_data_pipeline.py", line 4, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2024-11-02T20:54:31.699+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_data_pipeline.py
[2024-11-02T20:54:31.715+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_data_pipeline.py took 0.038 seconds
[2024-11-02T20:55:02.221+0000] {processor.py:186} INFO - Started process (PID=3680) to work on /opt/airflow/dags/stock_data_pipeline.py
[2024-11-02T20:55:02.222+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_data_pipeline.py for tasks to queue
[2024-11-02T20:55:02.224+0000] {logging_mixin.py:190} INFO - [2024-11-02T20:55:02.223+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/stock_data_pipeline.py
[2024-11-02T20:55:02.237+0000] {logging_mixin.py:190} INFO - [2024-11-02T20:55:02.234+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/stock_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_data_pipeline.py", line 4, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2024-11-02T20:55:02.238+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_data_pipeline.py
[2024-11-02T20:55:02.254+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_data_pipeline.py took 0.038 seconds
[2024-11-02T20:55:32.471+0000] {processor.py:186} INFO - Started process (PID=3743) to work on /opt/airflow/dags/stock_data_pipeline.py
[2024-11-02T20:55:32.472+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_data_pipeline.py for tasks to queue
[2024-11-02T20:55:32.474+0000] {logging_mixin.py:190} INFO - [2024-11-02T20:55:32.474+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/stock_data_pipeline.py
[2024-11-02T20:55:32.487+0000] {logging_mixin.py:190} INFO - [2024-11-02T20:55:32.484+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/stock_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_data_pipeline.py", line 4, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2024-11-02T20:55:32.488+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_data_pipeline.py
[2024-11-02T20:55:32.504+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_data_pipeline.py took 0.038 seconds
[2024-11-02T20:56:02.929+0000] {processor.py:186} INFO - Started process (PID=3806) to work on /opt/airflow/dags/stock_data_pipeline.py
[2024-11-02T20:56:02.930+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_data_pipeline.py for tasks to queue
[2024-11-02T20:56:02.932+0000] {logging_mixin.py:190} INFO - [2024-11-02T20:56:02.932+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/stock_data_pipeline.py
[2024-11-02T20:56:02.946+0000] {logging_mixin.py:190} INFO - [2024-11-02T20:56:02.943+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/stock_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_data_pipeline.py", line 4, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2024-11-02T20:56:02.947+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_data_pipeline.py
[2024-11-02T20:56:02.963+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_data_pipeline.py took 0.038 seconds
[2024-11-02T20:56:33.099+0000] {processor.py:186} INFO - Started process (PID=3869) to work on /opt/airflow/dags/stock_data_pipeline.py
[2024-11-02T20:56:33.099+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_data_pipeline.py for tasks to queue
[2024-11-02T20:56:33.101+0000] {logging_mixin.py:190} INFO - [2024-11-02T20:56:33.101+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/stock_data_pipeline.py
[2024-11-02T20:56:33.114+0000] {logging_mixin.py:190} INFO - [2024-11-02T20:56:33.112+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/stock_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_data_pipeline.py", line 4, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2024-11-02T20:56:33.115+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_data_pipeline.py
[2024-11-02T20:56:33.132+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_data_pipeline.py took 0.038 seconds
[2024-11-02T20:57:03.496+0000] {processor.py:186} INFO - Started process (PID=3933) to work on /opt/airflow/dags/stock_data_pipeline.py
[2024-11-02T20:57:03.497+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_data_pipeline.py for tasks to queue
[2024-11-02T20:57:03.498+0000] {logging_mixin.py:190} INFO - [2024-11-02T20:57:03.498+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/stock_data_pipeline.py
[2024-11-02T20:57:03.512+0000] {logging_mixin.py:190} INFO - [2024-11-02T20:57:03.509+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/stock_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_data_pipeline.py", line 4, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2024-11-02T20:57:03.513+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_data_pipeline.py
[2024-11-02T20:57:03.529+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_data_pipeline.py took 0.037 seconds
[2024-11-02T20:57:33.892+0000] {processor.py:186} INFO - Started process (PID=3996) to work on /opt/airflow/dags/stock_data_pipeline.py
[2024-11-02T20:57:33.893+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_data_pipeline.py for tasks to queue
[2024-11-02T20:57:33.895+0000] {logging_mixin.py:190} INFO - [2024-11-02T20:57:33.895+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/stock_data_pipeline.py
[2024-11-02T20:57:33.909+0000] {logging_mixin.py:190} INFO - [2024-11-02T20:57:33.906+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/stock_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_data_pipeline.py", line 4, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2024-11-02T20:57:33.910+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_data_pipeline.py
[2024-11-02T20:57:33.925+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_data_pipeline.py took 0.037 seconds
[2024-11-02T20:58:04.126+0000] {processor.py:186} INFO - Started process (PID=4059) to work on /opt/airflow/dags/stock_data_pipeline.py
[2024-11-02T20:58:04.127+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_data_pipeline.py for tasks to queue
[2024-11-02T20:58:04.129+0000] {logging_mixin.py:190} INFO - [2024-11-02T20:58:04.129+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/stock_data_pipeline.py
[2024-11-02T20:58:04.142+0000] {logging_mixin.py:190} INFO - [2024-11-02T20:58:04.139+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/stock_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_data_pipeline.py", line 4, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2024-11-02T20:58:04.143+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_data_pipeline.py
[2024-11-02T20:58:04.158+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_data_pipeline.py took 0.037 seconds
[2024-11-02T20:58:34.575+0000] {processor.py:186} INFO - Started process (PID=4122) to work on /opt/airflow/dags/stock_data_pipeline.py
[2024-11-02T20:58:34.575+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_data_pipeline.py for tasks to queue
[2024-11-02T20:58:34.577+0000] {logging_mixin.py:190} INFO - [2024-11-02T20:58:34.577+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/stock_data_pipeline.py
[2024-11-02T20:58:34.590+0000] {logging_mixin.py:190} INFO - [2024-11-02T20:58:34.587+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/stock_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_data_pipeline.py", line 4, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2024-11-02T20:58:34.591+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_data_pipeline.py
[2024-11-02T20:58:34.607+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_data_pipeline.py took 0.036 seconds
[2024-11-02T20:59:04.849+0000] {processor.py:186} INFO - Started process (PID=4185) to work on /opt/airflow/dags/stock_data_pipeline.py
[2024-11-02T20:59:04.850+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_data_pipeline.py for tasks to queue
[2024-11-02T20:59:04.852+0000] {logging_mixin.py:190} INFO - [2024-11-02T20:59:04.852+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/stock_data_pipeline.py
[2024-11-02T20:59:04.865+0000] {logging_mixin.py:190} INFO - [2024-11-02T20:59:04.862+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/stock_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_data_pipeline.py", line 4, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2024-11-02T20:59:04.866+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_data_pipeline.py
[2024-11-02T20:59:04.882+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_data_pipeline.py took 0.037 seconds
[2024-11-02T20:59:35.201+0000] {processor.py:186} INFO - Started process (PID=4248) to work on /opt/airflow/dags/stock_data_pipeline.py
[2024-11-02T20:59:35.202+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_data_pipeline.py for tasks to queue
[2024-11-02T20:59:35.203+0000] {logging_mixin.py:190} INFO - [2024-11-02T20:59:35.203+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/stock_data_pipeline.py
[2024-11-02T20:59:35.217+0000] {logging_mixin.py:190} INFO - [2024-11-02T20:59:35.214+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/stock_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_data_pipeline.py", line 4, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2024-11-02T20:59:35.218+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_data_pipeline.py
[2024-11-02T20:59:35.234+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_data_pipeline.py took 0.038 seconds
[2024-11-02T21:00:05.567+0000] {processor.py:186} INFO - Started process (PID=4311) to work on /opt/airflow/dags/stock_data_pipeline.py
[2024-11-02T21:00:05.567+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_data_pipeline.py for tasks to queue
[2024-11-02T21:00:05.569+0000] {logging_mixin.py:190} INFO - [2024-11-02T21:00:05.569+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/stock_data_pipeline.py
[2024-11-02T21:00:05.582+0000] {logging_mixin.py:190} INFO - [2024-11-02T21:00:05.579+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/stock_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_data_pipeline.py", line 4, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2024-11-02T21:00:05.583+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_data_pipeline.py
[2024-11-02T21:00:05.598+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_data_pipeline.py took 0.036 seconds
[2024-11-02T21:00:35.907+0000] {processor.py:186} INFO - Started process (PID=4374) to work on /opt/airflow/dags/stock_data_pipeline.py
[2024-11-02T21:00:35.908+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_data_pipeline.py for tasks to queue
[2024-11-02T21:00:35.910+0000] {logging_mixin.py:190} INFO - [2024-11-02T21:00:35.910+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/stock_data_pipeline.py
[2024-11-02T21:00:35.923+0000] {logging_mixin.py:190} INFO - [2024-11-02T21:00:35.920+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/stock_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_data_pipeline.py", line 4, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2024-11-02T21:00:35.924+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_data_pipeline.py
[2024-11-02T21:00:35.942+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_data_pipeline.py took 0.040 seconds
[2024-11-02T21:01:06.270+0000] {processor.py:186} INFO - Started process (PID=4437) to work on /opt/airflow/dags/stock_data_pipeline.py
[2024-11-02T21:01:06.271+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_data_pipeline.py for tasks to queue
[2024-11-02T21:01:06.273+0000] {logging_mixin.py:190} INFO - [2024-11-02T21:01:06.273+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/stock_data_pipeline.py
[2024-11-02T21:01:06.287+0000] {logging_mixin.py:190} INFO - [2024-11-02T21:01:06.284+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/stock_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_data_pipeline.py", line 4, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2024-11-02T21:01:06.288+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_data_pipeline.py
[2024-11-02T21:01:06.303+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_data_pipeline.py took 0.038 seconds
[2024-11-02T21:01:36.489+0000] {processor.py:186} INFO - Started process (PID=4500) to work on /opt/airflow/dags/stock_data_pipeline.py
[2024-11-02T21:01:36.490+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_data_pipeline.py for tasks to queue
[2024-11-02T21:01:36.492+0000] {logging_mixin.py:190} INFO - [2024-11-02T21:01:36.491+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/stock_data_pipeline.py
[2024-11-02T21:01:36.505+0000] {logging_mixin.py:190} INFO - [2024-11-02T21:01:36.502+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/stock_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_data_pipeline.py", line 4, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2024-11-02T21:01:36.506+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_data_pipeline.py
[2024-11-02T21:01:36.522+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_data_pipeline.py took 0.038 seconds
[2024-11-02T21:02:06.778+0000] {processor.py:186} INFO - Started process (PID=4563) to work on /opt/airflow/dags/stock_data_pipeline.py
[2024-11-02T21:02:06.779+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_data_pipeline.py for tasks to queue
[2024-11-02T21:02:06.781+0000] {logging_mixin.py:190} INFO - [2024-11-02T21:02:06.781+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/stock_data_pipeline.py
[2024-11-02T21:02:06.796+0000] {logging_mixin.py:190} INFO - [2024-11-02T21:02:06.793+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/stock_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_data_pipeline.py", line 4, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2024-11-02T21:02:06.797+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_data_pipeline.py
[2024-11-02T21:02:06.816+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_data_pipeline.py took 0.042 seconds
[2024-11-02T21:02:36.992+0000] {processor.py:186} INFO - Started process (PID=4626) to work on /opt/airflow/dags/stock_data_pipeline.py
[2024-11-02T21:02:36.993+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_data_pipeline.py for tasks to queue
[2024-11-02T21:02:36.996+0000] {logging_mixin.py:190} INFO - [2024-11-02T21:02:36.995+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/stock_data_pipeline.py
[2024-11-02T21:02:37.013+0000] {logging_mixin.py:190} INFO - [2024-11-02T21:02:37.010+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/stock_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_data_pipeline.py", line 4, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2024-11-02T21:02:37.014+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_data_pipeline.py
[2024-11-02T21:02:37.031+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_data_pipeline.py took 0.046 seconds
[2024-11-02T21:03:07.291+0000] {processor.py:186} INFO - Started process (PID=4689) to work on /opt/airflow/dags/stock_data_pipeline.py
[2024-11-02T21:03:07.292+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_data_pipeline.py for tasks to queue
[2024-11-02T21:03:07.294+0000] {logging_mixin.py:190} INFO - [2024-11-02T21:03:07.294+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/stock_data_pipeline.py
[2024-11-02T21:03:07.309+0000] {logging_mixin.py:190} INFO - [2024-11-02T21:03:07.306+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/stock_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_data_pipeline.py", line 4, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2024-11-02T21:03:07.310+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_data_pipeline.py
[2024-11-02T21:03:07.326+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_data_pipeline.py took 0.041 seconds
[2024-11-02T21:03:37.812+0000] {processor.py:186} INFO - Started process (PID=4752) to work on /opt/airflow/dags/stock_data_pipeline.py
[2024-11-02T21:03:37.813+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_data_pipeline.py for tasks to queue
[2024-11-02T21:03:37.814+0000] {logging_mixin.py:190} INFO - [2024-11-02T21:03:37.814+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/stock_data_pipeline.py
[2024-11-02T21:03:37.828+0000] {logging_mixin.py:190} INFO - [2024-11-02T21:03:37.825+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/stock_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_data_pipeline.py", line 4, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2024-11-02T21:03:37.829+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_data_pipeline.py
[2024-11-02T21:03:37.846+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_data_pipeline.py took 0.039 seconds
[2024-11-02T21:04:08.155+0000] {processor.py:186} INFO - Started process (PID=4815) to work on /opt/airflow/dags/stock_data_pipeline.py
[2024-11-02T21:04:08.155+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_data_pipeline.py for tasks to queue
[2024-11-02T21:04:08.157+0000] {logging_mixin.py:190} INFO - [2024-11-02T21:04:08.157+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/stock_data_pipeline.py
[2024-11-02T21:04:08.171+0000] {logging_mixin.py:190} INFO - [2024-11-02T21:04:08.168+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/stock_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_data_pipeline.py", line 4, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2024-11-02T21:04:08.172+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_data_pipeline.py
[2024-11-02T21:04:08.187+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_data_pipeline.py took 0.037 seconds
[2024-11-02T21:04:38.420+0000] {processor.py:186} INFO - Started process (PID=4878) to work on /opt/airflow/dags/stock_data_pipeline.py
[2024-11-02T21:04:38.421+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_data_pipeline.py for tasks to queue
[2024-11-02T21:04:38.423+0000] {logging_mixin.py:190} INFO - [2024-11-02T21:04:38.422+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/stock_data_pipeline.py
[2024-11-02T21:04:38.436+0000] {logging_mixin.py:190} INFO - [2024-11-02T21:04:38.433+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/stock_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_data_pipeline.py", line 4, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2024-11-02T21:04:38.437+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_data_pipeline.py
[2024-11-02T21:04:38.453+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_data_pipeline.py took 0.038 seconds
[2024-11-02T21:05:08.811+0000] {processor.py:186} INFO - Started process (PID=4941) to work on /opt/airflow/dags/stock_data_pipeline.py
[2024-11-02T21:05:08.812+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_data_pipeline.py for tasks to queue
[2024-11-02T21:05:08.813+0000] {logging_mixin.py:190} INFO - [2024-11-02T21:05:08.813+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/stock_data_pipeline.py
[2024-11-02T21:05:08.827+0000] {logging_mixin.py:190} INFO - [2024-11-02T21:05:08.824+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/stock_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_data_pipeline.py", line 4, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2024-11-02T21:05:08.828+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_data_pipeline.py
[2024-11-02T21:05:08.843+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_data_pipeline.py took 0.037 seconds
[2024-11-02T21:05:39.086+0000] {processor.py:186} INFO - Started process (PID=5004) to work on /opt/airflow/dags/stock_data_pipeline.py
[2024-11-02T21:05:39.087+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_data_pipeline.py for tasks to queue
[2024-11-02T21:05:39.088+0000] {logging_mixin.py:190} INFO - [2024-11-02T21:05:39.088+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/stock_data_pipeline.py
[2024-11-02T21:05:39.101+0000] {logging_mixin.py:190} INFO - [2024-11-02T21:05:39.099+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/stock_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_data_pipeline.py", line 4, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2024-11-02T21:05:39.102+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_data_pipeline.py
[2024-11-02T21:05:39.118+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_data_pipeline.py took 0.037 seconds
[2024-11-02T21:06:09.302+0000] {processor.py:186} INFO - Started process (PID=5067) to work on /opt/airflow/dags/stock_data_pipeline.py
[2024-11-02T21:06:09.303+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_data_pipeline.py for tasks to queue
[2024-11-02T21:06:09.305+0000] {logging_mixin.py:190} INFO - [2024-11-02T21:06:09.305+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/stock_data_pipeline.py
[2024-11-02T21:06:09.318+0000] {logging_mixin.py:190} INFO - [2024-11-02T21:06:09.315+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/stock_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_data_pipeline.py", line 4, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2024-11-02T21:06:09.319+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_data_pipeline.py
[2024-11-02T21:06:09.334+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_data_pipeline.py took 0.036 seconds
[2024-11-02T21:06:39.579+0000] {processor.py:186} INFO - Started process (PID=5130) to work on /opt/airflow/dags/stock_data_pipeline.py
[2024-11-02T21:06:39.580+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_data_pipeline.py for tasks to queue
[2024-11-02T21:06:39.582+0000] {logging_mixin.py:190} INFO - [2024-11-02T21:06:39.582+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/stock_data_pipeline.py
[2024-11-02T21:06:39.596+0000] {logging_mixin.py:190} INFO - [2024-11-02T21:06:39.593+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/stock_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_data_pipeline.py", line 4, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2024-11-02T21:06:39.597+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_data_pipeline.py
[2024-11-02T21:06:39.613+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_data_pipeline.py took 0.038 seconds
[2024-11-02T21:07:09.920+0000] {processor.py:186} INFO - Started process (PID=5193) to work on /opt/airflow/dags/stock_data_pipeline.py
[2024-11-02T21:07:09.921+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_data_pipeline.py for tasks to queue
[2024-11-02T21:07:09.923+0000] {logging_mixin.py:190} INFO - [2024-11-02T21:07:09.923+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/stock_data_pipeline.py
[2024-11-02T21:07:09.936+0000] {logging_mixin.py:190} INFO - [2024-11-02T21:07:09.933+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/stock_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_data_pipeline.py", line 4, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2024-11-02T21:07:09.937+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_data_pipeline.py
[2024-11-02T21:07:09.953+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_data_pipeline.py took 0.037 seconds
[2024-11-02T21:07:40.332+0000] {processor.py:186} INFO - Started process (PID=5256) to work on /opt/airflow/dags/stock_data_pipeline.py
[2024-11-02T21:07:40.333+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_data_pipeline.py for tasks to queue
[2024-11-02T21:07:40.335+0000] {logging_mixin.py:190} INFO - [2024-11-02T21:07:40.334+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/stock_data_pipeline.py
[2024-11-02T21:07:40.348+0000] {logging_mixin.py:190} INFO - [2024-11-02T21:07:40.345+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/stock_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_data_pipeline.py", line 4, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2024-11-02T21:07:40.349+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_data_pipeline.py
[2024-11-02T21:07:40.364+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_data_pipeline.py took 0.037 seconds
[2024-11-02T21:08:10.631+0000] {processor.py:186} INFO - Started process (PID=5319) to work on /opt/airflow/dags/stock_data_pipeline.py
[2024-11-02T21:08:10.632+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_data_pipeline.py for tasks to queue
[2024-11-02T21:08:10.634+0000] {logging_mixin.py:190} INFO - [2024-11-02T21:08:10.633+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/stock_data_pipeline.py
[2024-11-02T21:08:10.647+0000] {logging_mixin.py:190} INFO - [2024-11-02T21:08:10.644+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/stock_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_data_pipeline.py", line 4, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2024-11-02T21:08:10.648+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_data_pipeline.py
[2024-11-02T21:08:10.664+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_data_pipeline.py took 0.037 seconds
[2024-11-02T21:08:40.834+0000] {processor.py:186} INFO - Started process (PID=5382) to work on /opt/airflow/dags/stock_data_pipeline.py
[2024-11-02T21:08:40.835+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_data_pipeline.py for tasks to queue
[2024-11-02T21:08:40.838+0000] {logging_mixin.py:190} INFO - [2024-11-02T21:08:40.837+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/stock_data_pipeline.py
[2024-11-02T21:08:40.852+0000] {logging_mixin.py:190} INFO - [2024-11-02T21:08:40.849+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/stock_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_data_pipeline.py", line 4, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2024-11-02T21:08:40.853+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_data_pipeline.py
[2024-11-02T21:08:40.872+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_data_pipeline.py took 0.043 seconds
[2024-11-02T21:09:11.092+0000] {processor.py:186} INFO - Started process (PID=5441) to work on /opt/airflow/dags/stock_data_pipeline.py
[2024-11-02T21:09:11.093+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_data_pipeline.py for tasks to queue
[2024-11-02T21:09:11.095+0000] {logging_mixin.py:190} INFO - [2024-11-02T21:09:11.095+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/stock_data_pipeline.py
[2024-11-02T21:09:11.108+0000] {logging_mixin.py:190} INFO - [2024-11-02T21:09:11.106+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/stock_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_data_pipeline.py", line 4, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2024-11-02T21:09:11.109+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_data_pipeline.py
[2024-11-02T21:09:11.125+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_data_pipeline.py took 0.038 seconds
[2024-11-02T21:09:41.164+0000] {processor.py:186} INFO - Started process (PID=5495) to work on /opt/airflow/dags/stock_data_pipeline.py
[2024-11-02T21:09:41.165+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_data_pipeline.py for tasks to queue
[2024-11-02T21:09:41.167+0000] {logging_mixin.py:190} INFO - [2024-11-02T21:09:41.167+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/stock_data_pipeline.py
[2024-11-02T21:09:41.180+0000] {logging_mixin.py:190} INFO - [2024-11-02T21:09:41.178+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/stock_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_data_pipeline.py", line 4, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2024-11-02T21:09:41.181+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_data_pipeline.py
[2024-11-02T21:09:41.198+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_data_pipeline.py took 0.039 seconds
[2024-11-02T21:10:11.688+0000] {processor.py:186} INFO - Started process (PID=5557) to work on /opt/airflow/dags/stock_data_pipeline.py
[2024-11-02T21:10:11.688+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_data_pipeline.py for tasks to queue
[2024-11-02T21:10:11.691+0000] {logging_mixin.py:190} INFO - [2024-11-02T21:10:11.690+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/stock_data_pipeline.py
[2024-11-02T21:10:11.704+0000] {logging_mixin.py:190} INFO - [2024-11-02T21:10:11.701+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/stock_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_data_pipeline.py", line 4, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2024-11-02T21:10:11.705+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_data_pipeline.py
[2024-11-02T21:10:11.721+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_data_pipeline.py took 0.038 seconds
[2024-11-02T21:10:41.842+0000] {processor.py:186} INFO - Started process (PID=5618) to work on /opt/airflow/dags/stock_data_pipeline.py
[2024-11-02T21:10:41.843+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/stock_data_pipeline.py for tasks to queue
[2024-11-02T21:10:41.845+0000] {logging_mixin.py:190} INFO - [2024-11-02T21:10:41.845+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/stock_data_pipeline.py
[2024-11-02T21:10:41.858+0000] {logging_mixin.py:190} INFO - [2024-11-02T21:10:41.856+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/stock_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/stock_data_pipeline.py", line 4, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2024-11-02T21:10:41.859+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/stock_data_pipeline.py
[2024-11-02T21:10:41.875+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/stock_data_pipeline.py took 0.038 seconds
